CFLAGS =  -Wall -Wextra -I. -g -std=c++11

CFLAGS += -pedantic
CFLAGS += -pedantic-errors

CFLAGS += -Wmissing-include-dirs
CFLAGS += -Wfloat-equal
CFLAGS += -Wredundant-decls
CFLAGS += -Winit-self
CFLAGS += -Wshadow
CFLAGS += -Wconversion

all:
	-g++ $(CFLAGS) -o one.exe assign1p1.cpp
	-g++ $(CFLAGS) -o two.exe assign1p2.cpp