all: 
	-g++ -std=c++11 -Wall -I. -I../.. -g Item.cpp Armor.cpp Weapon.cpp RangedWeapon.cpp itemHeirarchyTester.cpp -o item.exe
	-g++ -std=c++11 -Wall -I. -I../.. -g Item.cpp Armor.cpp Weapon.cpp RangedWeapon.cpp Character.cpp itemHeirarchyTester.cpp characterTester.cpp -o character.exe
