CFLAGS =  -Wall -Wextra -I. -g -std=c++11

CFLAGS += -pedantic

CFLAGS += -Wmissing-include-dirs
CFLAGS += -Wfloat-equal
CFLAGS += -Wredundant-decls
CFLAGS += -Winit-self
CFLAGS += -Wshadow
CFLAGS += -Wconversion

all:
	-g++ $(CFLAGS) -o test1.exe tictactest1.cpp *oe.cpp
	-g++ $(CFLAGS) -o test2.exe tictactest2.cpp *oe.cpp
	-g++ $(CFLAGS) -o test3.exe tictactest3.cpp *oe.cpp